spring:
  jpa:
    properties:
      hibernate:
        naming:
          implicit-strategy: "org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl"
        default_schema: "public"
        format-sql: true
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    show-sql: false
  datasource:
    url: "jdbc:postgresql://localhost:5432/yuyukobot"
    username: "postgres"
    password: "pwd"
    driver-class-mame: "org.postgresql.Driver"
    continue-on-error: true
